#For localhost at 9595 http port
#spring.datasource.url=jdbc:mysql://localhost:3306/herplat?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=admin@123

#For www.cardirehab.com or cardirehab.com at 8444 https port. Also remember to change the pom.xml for apps real/root name(crehab).
spring.datasource.url=jdbc:mysql://localhost:3306/chsuser_herplat?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
spring.datasource.username=chsuser_root
spring.datasource.password=Admin@123

#For preprod.cardirehab.com at 8444 https port. Also remember to change the pom.xml for apps real/root name(preprodcrehab).
#spring.datasource.url=jdbc:mysql://localhost:3306/chsuser_preprodherplat?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
#spring.datasource.username=chsuser_pproot
#spring.datasource.password=Admin@123

#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto = create
logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.file.name=../logs/mylog.log

# App Properties
# server.port=9595
server.port=8444

# Base path for Secure file access on local server
# secure.files.base-path=C:/reactjs_workspace/CR_2.2/cardirehab/secure_files/files
# Base path for Secure file access on production or preprod server
secure.files.base-path=/var/secure_files/files

# Setting the session timeout
server.servlet.session.timeout=120m
#server.servlet.session.timeout=2m

# JWT secret signature key
jwt.secret=CardiRehabSecretKeyX12138yAn4

# JWT session expiration time
#cardirehab.app.jwtExpirationMs=7200000 //2 Hrs 

# MyVariables
#server.servlet.session.cookie.same-site:none
#server.servlet.session.cookie.secure:true

# File Upload / Download variables
spring.servlet.multipart.enabled=true

# Threshold after which files are written to disk
spring.servlet.multipart.file-size-threshold=2KB

# Max file size
spring.servlet.multipart.max-file-size=200MB

# Max Request Size
spring.servlet.multipart.max-request-size=215MB

#server.servlet.context-path=/
#server.ssl.enabled:true
#server.ssl.key-alias:local_ssl
#server.ssl.key-store:classpath:local-ssl.jks
#server.ssl.key-store-type:JKS
#server.ssl.key-password:admin@123
#server.ssl.key-store-password:admin@123
